[CmdletBinding()]
param([Parameter(Mandatory)][string] $IncidentPath,[string] $ConfigPath=(Join-Path (Split-Path -Parent $PSScriptRoot) 'config\agents.json'),[string] $CodexHome)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$incident=Get-Content -LiteralPath $IncidentPath -Raw -Encoding UTF8|ConvertFrom-Json
$server=[string]$incident.server;$signature=[string]$incident.failureSignature
try {
    # This worker deliberately receives no MCP configuration or session.  Health repair is independent of the failed transport.
    $health=& (Join-Path $PSScriptRoot 'Invoke-EcosystemHealthCheck.ps1') -Repair -ConfigPath $ConfigPath -CodexHome $CodexHome
    $failedChecks=@($health.Result.checks|Where-Object{[string]$_.status -eq 'failed'})
    $healthAccepted=($health.Result -and [string]$health.Result.status -in @('healthy','repaired')) -or ([string]$health.Result.status -eq 'degraded' -and -not $failedChecks.Count)
    if(-not $healthAccepted){throw 'Full ecosystem health validation contains failed checks; source repair is required before MCP canary recovery.'}
    $probe=& (Join-Path $PSScriptRoot 'Test-McpServerHealth.ps1') -ServerName $server -ConfigPath $ConfigPath -CodexHome $CodexHome
    if([bool]$probe.Healthy){$state=& (Join-Path $PSScriptRoot 'Set-McpCircuitState.ps1') -ServerName $server -State 'half-open' -FailureSignature $signature -ConfigPath $ConfigPath -CodexHome $CodexHome;$incident.status=[string]$state.state}else{$incident.status='waiting-for-repair';$incident.reason=[string]$probe.Reason}
} catch {$incident.status='source-repair-required';$incident.reason=$_.Exception.Message;$incident.sourceRepair=[ordered]@{runner='Invoke-EcosystemHealthCheck.ps1';mcpDisabled=$true;externalWrites=$false;productCodeChanges=$false;requestedAtUtc=[DateTime]::UtcNow.ToString('o')};if($incident.taskId -and $incident.agentId -and $incident.failurePath -and (Test-Path -LiteralPath $incident.failurePath)){try{$env:ECOSYSTEM_MCP_DISABLED='true';$dispatch=& (Join-Path $PSScriptRoot 'Start-AgentHealthRecovery.ps1') -TaskId ([string]$incident.taskId) -FailurePath ([string]$incident.failurePath) -ExecutionRunId ([string]$incident.executionRunId) -WorkspaceLeaseId ([string]$incident.workspaceLeaseId) -SuppressExternalDelivery -SuppressTargetedResume -ConfigPath $ConfigPath -CodexHome $CodexHome;$incident.sourceRepair.dispatchStatus=[string]$dispatch.Status}catch{$incident.sourceRepair.dispatchError=$_.Exception.Message}}}
$incident.completedAtUtc=[DateTime]::UtcNow.ToString('o');$tmp=$IncidentPath+'.tmp';[IO.File]::WriteAllText($tmp,(($incident|ConvertTo-Json -Depth 8)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));Move-Item -LiteralPath $tmp -Destination $IncidentPath -Force
$queueRoot=Split-Path -Parent $IncidentPath;$queueLock=Join-Path $queueRoot '.recovery.lock';$queueStream=[IO.File]::Open($queueLock,[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);$next=$null;try{$next=@(Get-ChildItem $queueRoot -Filter '*.json'|ForEach-Object{try{[pscustomobject]@{Path=$_.FullName;Value=(Get-Content $_.FullName -Raw|ConvertFrom-Json)}}catch{}}|Where-Object{[string]$_.Value.status -eq 'queued'}|Sort-Object {[DateTime]::Parse([string]$_.Value.createdAtUtc)}|Select-Object -First 1);if($next.Count){$queued=$next[0].Value;$queued.status='repairing';$queuedTmp=$next[0].Path+'.tmp';[IO.File]::WriteAllText($queuedTmp,(($queued|ConvertTo-Json -Depth 8)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));Move-Item -LiteralPath $queuedTmp -Destination $next[0].Path -Force}}finally{$queueStream.Dispose()};if($next.Count){$args=@('-NoProfile','-File',(Join-Path $PSScriptRoot 'Invoke-McpHealthRecoveryWorker.ps1'),'-IncidentPath',$next[0].Path,'-ConfigPath',$ConfigPath);if($CodexHome){$args+=@('-CodexHome',$CodexHome)};Start-Process -FilePath 'powershell' -ArgumentList $args -WindowStyle Hidden|Out-Null}
