[CmdletBinding()]
param([Parameter(Mandatory)][string] $ServerName,[Parameter(Mandatory)][string] $FailureSignature,[string] $TaskId,[string] $AgentId,[string] $FailurePath,[string] $ExecutionRunId,[string] $WorkspaceLeaseId,[switch] $NoStartWorker,[string] $ConfigPath=(Join-Path (Split-Path -Parent $PSScriptRoot) 'config\agents.json'),[string] $CodexHome)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if(-not(Get-Command Get-EcosystemStateRoot -ErrorAction SilentlyContinue)){Import-Module (Join-Path $PSScriptRoot 'AgentEcosystem.psm1') -Global}
$config=Get-EcosystemConfig -ConfigPath $ConfigPath -CodexHome $CodexHome;$root=Join-Path (Get-EcosystemStateRoot -Config $config -CodexHome $CodexHome) 'health\mcp-incidents';New-Item -ItemType Directory -Path $root -Force|Out-Null;$globalLock=Join-Path $root '.recovery.lock';$lockStream=[IO.File]::Open($globalLock,[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None)
$existing=@(Get-ChildItem $root -Filter '*.json' -ErrorAction SilentlyContinue|ForEach-Object{try{[pscustomobject]@{Path=$_.FullName;Value=(Get-Content $_.FullName -Raw|ConvertFrom-Json)}}catch{}}|Where-Object{[string]$_.Value.server -eq $ServerName -and [string]$_.Value.failureSignature -eq $FailureSignature -and [string]$_.Value.taskId -eq $TaskId -and [string]$_.Value.executionRunId -eq $ExecutionRunId -and [string]$_.Value.status -in @('queued','repairing')}|Select-Object -First 1);if($existing.Count){$lockStream.Dispose();return [pscustomobject]@{IncidentPath=$existing[0].Path;Deduplicated=$true;Status=[string]$existing[0].Value.status;McpDisabled=$true}}
$path=Join-Path $root ($ServerName+'-'+$FailureSignature+'-'+([guid]::NewGuid().ToString('N'))+'.json')
$active=@(Get-ChildItem $root -Filter '*.json' -ErrorAction SilentlyContinue|ForEach-Object{try{Get-Content $_.FullName -Raw|ConvertFrom-Json}catch{}}|Where-Object{[string]$_.status -eq 'repairing'});if($active.Count -ge [int]$config.mcp.resilience.maxConcurrentRepairs){$queued=[ordered]@{server=$ServerName;failureSignature=$FailureSignature;taskId=$TaskId;agentId=$AgentId;failurePath=$FailurePath;executionRunId=$ExecutionRunId;workspaceLeaseId=$WorkspaceLeaseId;createdAtUtc=[DateTime]::UtcNow.ToString('o');status='queued';mcpDisabled=$true};$temporary=$path+'.'+[guid]::NewGuid().ToString('N')+'.tmp';[IO.File]::WriteAllText($temporary,(($queued|ConvertTo-Json)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));Move-Item -LiteralPath $temporary -Destination $path -Force;$lockStream.Dispose();return [pscustomobject]@{IncidentPath=$path;Deduplicated=$false;Status='queued';McpDisabled=$true}}
$incident=[ordered]@{server=$ServerName;failureSignature=$FailureSignature;taskId=$TaskId;agentId=$AgentId;failurePath=$FailurePath;executionRunId=$ExecutionRunId;workspaceLeaseId=$WorkspaceLeaseId;createdAtUtc=[DateTime]::UtcNow.ToString('o');status='repairing';mcpDisabled=$true}
$temporary=$path+'.'+[guid]::NewGuid().ToString('N')+'.tmp';[IO.File]::WriteAllText($temporary,(($incident|ConvertTo-Json)+[Environment]::NewLine),(New-Object Text.UTF8Encoding($false)));Move-Item -LiteralPath $temporary -Destination $path -Force
$worker=Join-Path $PSScriptRoot 'Invoke-McpHealthRecoveryWorker.ps1'
$arguments=@('-NoProfile','-File',$worker,'-IncidentPath',$path,'-ConfigPath',$ConfigPath)
if($CodexHome){$arguments+=@('-CodexHome',$CodexHome)}
$process=$null;try{if(-not $NoStartWorker){$process=Start-Process -FilePath 'powershell' -ArgumentList $arguments -WindowStyle Hidden -PassThru}}finally{$lockStream.Dispose()}
[pscustomobject]@{IncidentPath=$path;Deduplicated=$false;Status='repairing';McpDisabled=$true;ProcessId=if($process){$process.Id}else{$null}}
