[CmdletBinding(SupportsShouldProcess)]
param([Parameter(Mandatory)][ValidatePattern('^[A-Za-z0-9._-]+$')][string]$TaskId,[Parameter(Mandatory)][ValidatePattern('^[a-z][a-z0-9_]*$')][string]$AgentId,[Parameter(Mandatory)][ValidateSet('codex','copilot','claude')][string]$Provider,[switch]$Resume,[string]$ConfigPath=(Join-Path (Split-Path -Parent $PSScriptRoot) 'config\agents.json'),[string]$CodexHome)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';Import-Module (Join-Path $PSScriptRoot 'AgentEcosystem.psm1') -Force
$config=Get-EcosystemConfig -ConfigPath $ConfigPath -CodexHome $CodexHome;$agent=@($config.agents|Where-Object{[string]$_.id -eq $AgentId}|Select-Object -First 1);if(-not $agent){throw "Unknown agent '$AgentId'."};if(-not $config.providerRouting.providers.PSObject.Properties[$Provider]){throw "Unsupported provider '$Provider'."}
$taskRoot=Join-Path (Get-EcosystemStateRoot -Config $config -CodexHome $CodexHome) "tasks\$TaskId";$taskPath=Join-Path $taskRoot 'task.json';if(-not(Test-Path -LiteralPath $taskPath)){throw "Task '$TaskId' was not found."};$task=Get-Content $taskPath -Raw -Encoding utf8|ConvertFrom-Json;$state=$task.agentStatuses.PSObject.Properties[$AgentId].Value
if([string]$state.status -eq 'running'){& (Join-Path $PSScriptRoot 'Save-AgentCheckpoint.ps1') -TaskId $TaskId -AgentId $AgentId -Reason 'provider-switch' -ConfigPath $ConfigPath -CodexHome $CodexHome|Out-Null;if($task.workflowProcessId){Stop-Process -Id ([int]$task.workflowProcessId) -Force -ErrorAction SilentlyContinue};& (Join-Path $PSScriptRoot 'Set-AgentTaskStatus.ps1') -TaskId $TaskId -AgentId $AgentId -AgentStatus waiting -Stage provider_switch -Message "Provider switch requested: checkpoint saved; restart required." -ConfigPath $ConfigPath -CodexHome $CodexHome|Out-Null}
if($PSCmdlet.ShouldProcess($AgentId,"Switch provider to $Provider")){$agent.provider=$Provider;Write-Utf8NoBomAtomic -Path $ConfigPath -Content (($config|ConvertTo-Json -Depth 40)+[Environment]::NewLine);& (Join-Path $PSScriptRoot 'Add-TaskEvent.ps1') -TaskId $TaskId -Actor $AgentId -Type provider-switched -Summary "Provider changed to '$Provider'." -ConfigPath $ConfigPath -CodexHome $CodexHome|Out-Null}
if($Resume){& (Join-Path $PSScriptRoot 'Start-DevelopmentWorkflow.ps1') -Mode ([string]$task.mode) -TaskId $TaskId -TaskSelector ([string]$task.selector) -Resume -TargetAgentId $AgentId -ConfigPath $ConfigPath -CodexHome $CodexHome}
[pscustomobject]@{taskId=$TaskId;agentId=$AgentId;provider=$Provider;resumed=[bool]$Resume}
