[CmdletBinding()]
param(
    [string] $ConfigPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'config\agents.json'),
    [string] $CodexHome,
    [string] $OutputDirectory,
    [switch] $Install
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'AgentEcosystem.psm1') -Force

$config = Get-EcosystemConfig -ConfigPath $ConfigPath -CodexHome $CodexHome
$resolvedCodexHome = Get-DefaultCodexHome -Override $CodexHome
if ($Install) {
    $OutputDirectory = Resolve-EcosystemPath -Value ([string]$config.runtime.agentInstallRoot) -Config $config -CodexHome $resolvedCodexHome
}
elseif (-not $OutputDirectory) {
    $OutputDirectory = Join-Path (Get-EcosystemRoot) '.runtime\generated\agents'
}
$OutputDirectory = [IO.Path]::GetFullPath($OutputDirectory)
New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

$written = [Collections.Generic.List[string]]::new()
foreach ($agent in @($config.agents)) {
    $target = Join-Path $OutputDirectory "$($agent.name).toml"
    if ((Test-Path -LiteralPath $target) -and $Install) {
        $firstLine = Get-Content -LiteralPath $target -TotalCount 1
        if ($firstLine -ne '# Generated by development-agent-ecosystem. Edit config/agents.json and prompt files, not this file.') {
            throw "Refusing to overwrite non-generated agent file: $target"
        }
    }
    $temporary = "$target.tmp"
    Write-Utf8NoBom -Path $temporary -Content (New-AgentToml -Agent $agent -Config $config -CodexHome $resolvedCodexHome)
    Move-Item -LiteralPath $temporary -Destination $target -Force
    $written.Add($target)
}

[pscustomobject]@{
    ConfigPath = [IO.Path]::GetFullPath($ConfigPath)
    OutputDirectory = $OutputDirectory
    Installed = [bool]$Install
    AgentFiles = @($written)
}

